# This Dockerfile is used to let Dependabot manage pinned versions of tools that
# will be installed using the target `make install`

# Keep these sorted alphabetically, separated by an empty line

FROM hashicorp/packer:1.13.0 as packer

FROM hashicorp/terraform:1.12.1 as terraform
