# This Dockerfile is used to let Dependabot manage pinned versions of tools that
# will be installed using the target `make install`

# Keep these sorted alphabetically, separated by an empty line

FROM hashicorp/packer:1.9.4 as packer

FROM hashicorp/terraform:1.6.0 as terraform
